version: '3.7'

services:

  wrs:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: wrs
    restart: unless-stopped
    ports:
      - "8000"

  nginx:
    restart: unless-stopped
    image: nginx:latest
    ports:
      - 80
    volumes:
      - ./app/dist:/var/www/
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - wrs:wrs
    environment:
      - VIRTUAL_HOST=wrs.local
      - VIRTUAL_PORT=80